CCM-5340: step to fail on non-zero test result

diff --git a/.github/actions/security-scan/action.yaml b/.github/actions/security-scan/action.yaml
--- a/.github/actions/security-scan/action.yaml
+++ b/.github/actions/security-scan/action.yaml
@@ -14,17 +14,21 @@ runs:
       run: npx -w=tests/security playwright install --with-deps
 
     - name: Run test - security scan
-      shell: bash
-      run: ./tests/security/run.sh
-
-    - name: Debug working directory
+      id: test
       shell: bash
       run: |
-        echo "Current working directory: $(pwd)"
-        ls -R tests/security
+        ./tests/security/run.sh
+        "exit_code=$?" >> $GITHUB_OUTPUT.
 
     - name: Archive security test results
       uses: actions/upload-artifact@v4
       with:
         name: Security test report
         path: "tests/security/zap-out-*.html"
+
+    - name: Fail workflow on test failure
+      shell: bash
+      if: steps.test.outputs.exit_code != 0
+      run: |
+        echo "Security tests failed with exit code ${{ steps.test.outputs.exit_code }}"
+        exit 1
